language: go

script:
- export
- go test -cover -coverprofile coverage.out
- go tool cover -func=coverage.out


deploy:
  provider: script
  skip_cleanup: true
  script: >-
    GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/jpedro/color@$TRAVIS_TAG
    cat go.mod
  on:
    tags: true
