name: Test

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        # go-version: 1.15.x
        go-version: 1.18.x

    # - name: Run the linters
    #   uses: golangci/golangci-lint-action@v3
    #   with:
    #     version: v1.29

    - name: Build the code
      run: |
        # go build -v ./...
        make build

    - name: Run the tests
      run: |
        # go test -v -covermode=count -coverprofile=coverage.out
        make test

    - name: Test the example
      run: |
        make example

    - name: Test the cli
      run: |
        export GOPATH="$PWD/tmp"
        mkdir -p $GOPATH
        echo "${GOROOT:-GOROOT is unset}"
        echo "${GOPATH:-GOPATH is unset}"

        go install github.com/jpedro/color/cli/color@refactor
        ls -la $PWD
        ls -la $GOPATH
        # $GOPATH/color --version
        # $GOPATH/color 'This is the default color'
        # $GOPATH/color orange 'And this is orange!'

    - name: Notify slack
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
